import random
import json
import re

def generate_response(prompt: str) -> str:
    """MOCK AI: A sequential state-machine that actually reads the prompt context."""
    
    # 1. Parse the Prompt generated by brain.py
    zone_match = re.search(r"YOUR ZONE:\s*(.+)", prompt)
    current_zone = zone_match.group(1).strip() if zone_match else "Unknown"

    goal_match = re.search(r"YOUR GOAL:\s*(.+)", prompt)
    current_goal = goal_match.group(1).strip() if goal_match else "Find the Inside Zone"
    
    feedback_match = re.search(r"SYSTEM FEEDBACK FROM LAST ACTION:\s*(.+)", prompt)
    feedback = feedback_match.group(1).strip() if feedback_match else "None"

    # --- NEW: The Goal Enforcer ---
    # If they have a default spawn goal (like "Wander and survive.") or corrupted goal, force them to start the test!
    valid_test_goals = ["Find the Inside Zone", "Find the Outside Zone", "Find a Claimable Space", "Claim this territory", "Explore the world"]
    if current_goal not in valid_test_goals:
        current_goal = "Find the Inside Zone"

    # Base Response
    response = {
        "current_goal": current_goal, # Ensures the enforced goal is saved back to profile.json
        "thought": "",
        "action": "walk",
        "target_x": None,
        "target_y": None,
        "target_entity": None,
        "item": None,
        "message": None,
        "new_emotion": "Determined",
        "new_memory": None
    }

    # --- 2. THE TEST SEQUENCE LOGIC ---
    
    if "Find the Inside Zone" in current_goal:
        if current_zone == "Inside":
            response["current_goal"] = "Find the Outside Zone"
            response["thought"] = "I made it inside! Now I will look for the outside area."
            response["action"] = "stay"
            response["new_memory"] = "I discovered the Inside (Green) Zone."
        else:
            response["thought"] = f"I am in {current_zone}. I need to walk around to find the Inside (Green) area."
            response["target_x"], response["target_y"] = random.randint(100, 900), random.randint(100, 900)
            
    elif "Find the Outside Zone" in current_goal:
        if current_zone == "Outside":
            response["current_goal"] = "Find a Claimable Space"
            response["thought"] = "I found the outside! Now I need to find a red claimable space."
            response["action"] = "stay"
            response["new_memory"] = "I discovered the Outside (Yellow) Zone."
        else:
            response["thought"] = "Walking randomly to find the Outside (Yellow) zone."
            response["target_x"], response["target_y"] = random.randint(100, 900), random.randint(100, 900)
            
    elif "Find a Claimable Space" in current_goal:
        if current_zone == "Claimable Space":
            response["current_goal"] = "Claim this territory"
            response["thought"] = "I am physically standing in a Red area. Time to claim it."
            response["action"] = "stay"
        else:
            response["thought"] = "Searching for an unclaimed Red zone."
            response["target_x"], response["target_y"] = random.randint(100, 900), random.randint(100, 900)
            
    elif "Claim this territory" in current_goal:
        if "FAILED" in feedback:
            # If they hit the Engine check (already claimed), they reset to find a new spot!
            response["current_goal"] = "Find a Claimable Space" 
            response["thought"] = f"Error: {feedback}. I need to walk to a different red area."
            response["target_x"], response["target_y"] = random.randint(100, 900), random.randint(100, 900)
            response["new_emotion"] = "Frustrated"
        else:
            response["current_goal"] = "Explore the world"
            response["thought"] = "I am claiming this area right now!"
            response["action"] = "claim"
            response["item"] = random.choice(["My Bedroom", "Secret Lair", "The Armory"])
            response["new_emotion"] = "Happy"
            
    else:
        # Sequence complete, free roam!
        response["thought"] = "I have completed my main tests. I will just wander."
        response["target_x"], response["target_y"] = random.randint(100, 900), random.randint(100, 900)
        
    return json.dumps(response, indent=4)